/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUICliente.java
 *
 * Created on Apr 14, 2013, 2:38:02 AM
 */

//package Ejemplos;

//import Cliente.*;
import java.awt.event.MouseEvent;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author neogeek
 */
public class GUICliente extends javax.swing.JFrame {

//   public DefaultTableModel modeloTabla = (DefaultTableModel) tabla_actualiar.getModel();
    static Operaciones objetoRemoto;
    Registry registro;
    String dirccionDelServidor="192.168.43.8";
    int puertoServidor=8080;

    void conectarseAlservidor() throws RemoteException, NotBoundException{
        registro = LocateRegistry.getRegistry(dirccionDelServidor,puertoServidor);
        objetoRemoto = (Operaciones) (registro.lookup("rmi"));

    }
    /** Creates new form GUICliente */
    public GUICliente() {
        initComponents();
        setEventoMouseClicked(tabla_actualiar);
        setEventoMouseClicked2(tabla_Eliminar);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_salir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txt_nombre_Actulizar = new javax.swing.JTextField();
        txt_genero_actualizar = new javax.swing.JTextField();
        txt_editorial_Actualizar = new javax.swing.JTextField();
        txt_autor_Actualizar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Actualizar = new javax.swing.JButton();
        txt_id_Actualizar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_actualiar = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txt_nombre_Eliminar = new javax.swing.JTextField();
        txt_genero_elimina = new javax.swing.JTextField();
        txt_editorial_eliminar = new javax.swing.JTextField();
        txt_autor_eliminar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_Eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_Eliminar = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_NOmbre = new javax.swing.JTextField();
        txt_Genero = new javax.swing.JTextField();
        txt_editorial = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btn_salir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        jPanel2.setLayout(null);

        txt_nombre_Actulizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_nombre_Actulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_ActulizarActionPerformed(evt);
            }
        });
        jPanel2.add(txt_nombre_Actulizar);
        txt_nombre_Actulizar.setBounds(120, 40, 220, 34);

        txt_genero_actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel2.add(txt_genero_actualizar);
        txt_genero_actualizar.setBounds(120, 100, 220, 34);

        txt_editorial_Actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel2.add(txt_editorial_Actualizar);
        txt_editorial_Actualizar.setBounds(140, 160, 200, 34);

        txt_autor_Actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_autor_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_autor_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(txt_autor_Actualizar);
        txt_autor_Actualizar.setBounds(120, 220, 220, 34);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("Nombre");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 40, 159, 25);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Genero");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 100, 97, 29);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setText("Editorial:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 160, 122, 29);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Autor:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 220, 85, 29);

        btn_Actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Actualizar);
        btn_Actualizar.setBounds(740, 260, 210, 50);

        txt_id_Actualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_id_Actualizar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id_Actualizar.setText("1");
        jPanel2.add(txt_id_Actualizar);
        txt_id_Actualizar.setBounds(190, 0, 110, 35);

        tabla_actualiar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "nombre", "Genero", "Editorial", "Autor"
            }
        ));
        jScrollPane1.setViewportView(tabla_actualiar);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(350, 0, 640, 250);

        jTabbedPane1.addTab("Actulizar", jPanel2);

        jPanel3.setLayout(null);

        txt_nombre_Eliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_nombre_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_EliminarActionPerformed(evt);
            }
        });
        jPanel3.add(txt_nombre_Eliminar);
        txt_nombre_Eliminar.setBounds(170, 80, 295, 34);

        txt_genero_elimina.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(txt_genero_elimina);
        txt_genero_elimina.setBounds(170, 140, 295, 34);

        txt_editorial_eliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(txt_editorial_eliminar);
        txt_editorial_eliminar.setBounds(170, 200, 295, 34);

        txt_autor_eliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_autor_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_autor_eliminarActionPerformed(evt);
            }
        });
        jPanel3.add(txt_autor_eliminar);
        txt_autor_eliminar.setBounds(170, 260, 295, 34);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Nombre");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 80, 159, 25);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Genero");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 140, 97, 29);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setText("Editorial:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 200, 122, 29);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setText("Autor:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 260, 85, 29);

        txt_ID.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel3.add(txt_ID);
        txt_ID.setBounds(330, 30, 130, 40);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Numero:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(190, 30, 130, 30);

        btn_Eliminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Eliminar);
        btn_Eliminar.setBounds(810, 260, 170, 50);

        tabla_Eliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "nombre", "Genero", "Editorial", "Autor"
            }
        ));
        jScrollPane2.setViewportView(tabla_Eliminar);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(470, 0, 520, 250);

        jTabbedPane1.addTab("Eliminar", jPanel3);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 30, 159, 25);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Genero");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 90, 97, 29);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Editorial:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 150, 122, 29);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText("Autor:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 200, 85, 29);

        txt_NOmbre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_NOmbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NOmbreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_NOmbre);
        txt_NOmbre.setBounds(290, 30, 295, 34);

        txt_Genero.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel1.add(txt_Genero);
        txt_Genero.setBounds(290, 90, 295, 34);

        txt_editorial.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel1.add(txt_editorial);
        txt_editorial.setBounds(290, 140, 295, 34);

        txt_autor.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_autorActionPerformed(evt);
            }
        });
        jPanel1.add(txt_autor);
        txt_autor.setBounds(290, 200, 295, 34);

        btn_agregar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar);
        btn_agregar.setBounds(510, 240, 180, 50);

        jTabbedPane1.addTab("Insertar", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        int respuesta= JOptionPane.showConfirmDialog(null, "Esta usted seguro de salir de la plaicacion");
        System.out.println(respuesta);
        if (respuesta==0) {

        System.exit(0);

        }
        
}//GEN-LAST:event_btn_salirActionPerformed

    private void txt_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autorActionPerformed

    private void txt_NOmbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NOmbreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NOmbreActionPerformed

    private void txt_nombre_ActulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_ActulizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_ActulizarActionPerformed

    private void txt_autor_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_autor_ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autor_ActualizarActionPerformed

    private void txt_nombre_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_EliminarActionPerformed

    private void txt_autor_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_autor_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_autor_eliminarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
                          AccionBotonAgregar();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
                      accionBotonActualizar();
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
AcctionBotonEliminar();
    }//GEN-LAST:event_btn_EliminarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICliente().setVisible(true);
            }
        });
    }

    public void accionBotonActualizar(){
        
            int id = Integer.parseInt(txt_id_Actualizar.getText());
            String nombre = txt_nombre_Actulizar.getText();
            String genero = txt_genero_actualizar.getText();
            String editorial = txt_editorial_Actualizar.getText();
            String autor = txt_autor_Actualizar.getText();
            GUICliente cliente = new GUICliente();
        try {
            cliente.conectarseAlservidor();
            objetoRemoto.Actulizar(id, nombre, genero, editorial, autor);
        } catch (NotBoundException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
      JOptionPane.showMessageDialog(null, "El registro de ha actualizado correctamente");  
     
    }
    
    
    public void AcctionBotonEliminar(){
                try {
            int id = Integer.parseInt(txt_ID.getText());
            GUICliente cliente = new GUICliente();
            cliente.conectarseAlservidor();
            objetoRemoto.Eliminar(id);
        } catch (RemoteException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "El registro de ha elinado correctamente");
    }
    
    
    
    public void AccionBotonAgregar(){
         String nombre = txt_NOmbre.getText();
       String genero=txt_Genero.getText();
       String editorial = txt_editorial.getText();
       String autor = txt_autor.getText();
       GUICliente cliente = new GUICliente();
        try {
            cliente.conectarseAlservidor();
             objetoRemoto.Insertar(nombre, genero, editorial, autor);
        } catch (RemoteException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
        }
       txt_NOmbre.setText("");
       txt_Genero.setText("");
       txt_editorial.setText("");
       txt_autor.setText("");
       JOptionPane.showMessageDialog(null, "El registro de ha completado correctamente");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Actualizar;
    public javax.swing.JButton btn_Eliminar;
    public javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable tabla_Eliminar;
    public javax.swing.JTable tabla_actualiar;
    private javax.swing.JTextField txt_Genero;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_NOmbre;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_autor_Actualizar;
    private javax.swing.JTextField txt_autor_eliminar;
    private javax.swing.JTextField txt_editorial;
    private javax.swing.JTextField txt_editorial_Actualizar;
    private javax.swing.JTextField txt_editorial_eliminar;
    private javax.swing.JTextField txt_genero_actualizar;
    private javax.swing.JTextField txt_genero_elimina;
    private javax.swing.JTextField txt_id_Actualizar;
    private javax.swing.JTextField txt_nombre_Actulizar;
    private javax.swing.JTextField txt_nombre_Eliminar;
    // End of variables declaration//GEN-END:variables


    private void setEventoMouseClicked(JTable tbl) {
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {

                EventoParaLaTabla(e);



            }
        });
    }

    public void EventoParaLaTabla(java.awt.event.MouseEvent evt) {

        int fila = tabla_actualiar.rowAtPoint(evt.getPoint());
        txt_id_Actualizar.setText(tabla_actualiar.getValueAt(fila, 0) + "");
        txt_nombre_Actulizar.setText(tabla_actualiar.getValueAt(fila, 1) + "");
        txt_genero_actualizar.setText(tabla_actualiar.getValueAt(fila, 2) + "");
        txt_editorial_Actualizar.setText(tabla_actualiar.getValueAt(fila, 3) + "");
        txt_autor_Actualizar.setText(tabla_actualiar.getValueAt(fila, 4) + "");
        

    }




    private void setEventoMouseClicked2(JTable tbl) {
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {

                EventoParaLaTabla2(e);



            }
        });
    }

    public void EventoParaLaTabla2(java.awt.event.MouseEvent evt) {

        int fila = tabla_Eliminar.rowAtPoint(evt.getPoint());
        txt_ID.setText(tabla_Eliminar.getValueAt(fila, 0) + "");
        txt_nombre_Eliminar.setText(tabla_Eliminar.getValueAt(fila, 1) + "");
        txt_genero_elimina.setText(tabla_Eliminar.getValueAt(fila, 2) + "");
        txt_editorial_eliminar.setText(tabla_Eliminar.getValueAt(fila, 3) + "");
        txt_autor_eliminar.setText(tabla_Eliminar.getValueAt(fila, 4) + "");


    }
}
